version: '3.8'
services:
  # Frontend service (Next.js)
  frontend:
    image: teddymuli/aethly-frontend:latest
    container_name: frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  # Backend service (Go)
  backend:
    image: teddymuli/aethly-backend:latest
    container_name: backend
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/mydb
      - REDIS_URL=redis://redis:6379
      - ENV=production
      - DB_HOST=postgres
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  # PostgreSQL service
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2025Muli!
      POSTGRES_DB: aethly
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

# Define the networks for the containers to communicate
networks:
  app-network:

# Define volumes for data persistence
volumes:
  postgres_data:
